### ISSUE TITLE
Package hardwired to elm-core 4.0.0

### ISSUE THREAD

**Issue by berry** [elm-community/list-extra#4]
I wanted to use this library but the library is hardwired to elm-core 4.0.0 (elm-core is currently at 4.0.1). My suggestion is that this library should make the dependancy on elm-core a bit more lenient.

**Comment by jvoigtlaender** [comment]
I just checked around in the other `elm-community` packages, and there are two more that have this restrictive `"elm-lang/core": "4.0.0 <= v <= 4.0.0"` bound: https://github.com/elm-community/elm-webgl and https://github.com/elm-community/elm-linear-algebra. In all three cases (those other two, and the one at hand here), that exact bound was put in place by @eeue56. Maybe there was a specific reason for that approach?

**Comment by mgold** [comment]
The commit that changed the bounds, f4c9d344, is captioned "auto migrate". I think it's safe to assume this was a script error and not intentional. Richard and I fixed a similar error [here](https://github.com/elm-community/elm-lazy-list/pull/3).

The maintainer should update the deps and release a patch version. (If that doesn't happen in 24 hours someone else can do it.)

**Comment by eeue56** [comment]
Yes, this should be looser.

**Comment by abadi199** [comment]
I've loosen the `elm-lang/core` version restriction https://github.com/elm-community/list-extra/commit/6b4a68a1712bc8145365d9437a9e7d2fd353edc5, and published a new version:
http://package.elm-lang.org/packages/elm-community/list-extra/2.0.1/
