### ISSUE TITLE
Remove one of two functions with same implementation, generally make consistent names

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/list-extra#7]
`deleteIf` and `removeWhen` are the same function. I think the library should contain only one of them.

**Comment by jvoigtlaender** [comment]
Also, there's "removeAt", which might as well be called "deleteAt". The library could use a pass of making names consistent.

**Comment by jvoigtlaender** [comment]
The last comment, because there are also a bunch of "drop..." functions. What is the difference between deleting, removing, and dropping?

**Comment by shmookey** [comment]
_Edit: now that this issue is closed, I've cleaned up the following list to make it easier to refer back to._

If the goal is to go for consistent naming, then to me:
- filters operate over all elements of a list
- drops operate on a list prefix, conversely dropRights operate on a suffix
- removes operate on the first matching element[s] of a list
- deletes are not yet defined, this term is available for some other class of behaviour
- before suggesting that a function which is not a filter, drop or remove should be named 'delete', consider using a name that describes _what you get back_ rather than _what the function does_, e.g. instead of 'dropDuplicates', use 'unique' 

My `deleteFirst` (https://github.com/elm-community/list-extra/pull/6) operates on the first matching element, but that's just copying a Haskell convention. To my ear "delete" connotes erasing data from persistent storage, rather than merely discarding it from a data structure in memory. I'd prefer to clean up the other names and rename it to `remove`.

I would suggest:
- Start considering "remove" to suggest _operations on the first matching element_ of a list. 
- Keep `removeAt` because it fits this constraint. 
- Rename `removeWhen` to `filterNot` (or drop it entirely because it's trivial).
- Delete `deleteIf` because it's the same as `filterNot`.
- Accept my PR, but rename `deleteFirst` to `remove`, which is consistent with `Set.remove`

**Comment by jvoigtlaender** [comment]
What about the function currently called dropDuplicates?

And I assume there would be renaming of current dropWhileEnd to dropWhileRight, and analogously for takeWhileEnd?

**Comment by shmookey** [comment]
I think that makes sense. Re: `dropDuplicates`, I'm inclined to think of it in terms of what you get back - how about `uniques`?

Happy to put these changes in my PR.

**Comment by mgold** [comment]
In my [nonempty list](http://package.elm-lang.org/packages/mgold/elm-nonempty-list/2.0.1/List-Nonempty#deduplicate) library, I offer `uniq` and `dedup`. The former removes all duplicates, while the latter removes adjacent duplicates. I'm not thrilled with the abbreviations, but maybe `unique`, as a verb, rather than the plural noun?

**Comment by shmookey** [comment]
Yeah, sounds good. Updated #6.

**Comment by jvoigtlaender** [comment]
Some context about dropDuplicates/unique: https://github.com/elm-community/elm-list-extra/issues/31. 

Also, a change here affects https://github.com/elm-community/list-extra/pull/5, so bring this name change up there as well?
